### ISSUE TITLE
Add the bot to the official slack channel

### ISSUE THREAD

**Issue by Dan12** [Dan12/starter-ruby-bot#218]
## Why

Allow the team to be more productive

## Stories

As me, I want to roll this bot out so that I can get feedback and do bugtests

## Objectives

- [ ] do this before the end of this week (07/30)

## Definitions

1) what is a team?
- a team is the developers and business people at the company

2) what is productive?
- productive is working more efficiently

## Research questions

what is required for rolling out this feature?

## Behavior stories

when I got the the company slack, I should be able to interact with the bot and get more things done quicker

## New api endpoints

github api for the bot

## Tasks

- [ ] add the bot to the slack channel
- [ ] add all of the tokens to the config file
- [ ] invite it to the necessary channels
- [ ] test the bot out

**Comment by Dan12** [comment]
@Dan12:
Closed this issue and created pull request at https://github.com/Dan12/starter-ruby-bot/pull/219
