### ISSUE TITLE
Test feature

### ISSUE THREAD

**Issue by Dan12** [Dan12/starter-ruby-bot#98]
## Why

it is awesome

## Stories

i do this and that and use the feature

## Objectives

- [ ] make it awesome
- [ ] make it cool

## Work

- This feature is estimated to be **1** days of work
- This feature is dependant on none

## New files

awesome.html

## Tasks

- [ ] create hte routes
- [ ] create the things
- [ ] link the stuff

**Comment by Dan12** [comment]
Closed issue:
done with test feature
